name: NPM package

on:
  pull_request:
    branches:
      - master
      - preview
      - develop
  push:
    branches-ignore:
      - master
      - preview

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set Up Node environment
      uses: actions/setup-node@v2-beta
      with:
        node-version: '12'
    - name: Install dependencies
      run: npm install
    - name: CSS linting with stylelint
      run: npm run css-lint
    - name: JS linting with ESLint
      run: npm run js-lint
